-- MySQL Script generated by MySQL Workbench
-- Wed Jul  5 16:43:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema personal_website_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `personal_website_schema` ;

-- -----------------------------------------------------
-- Schema personal_website_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `personal_website_schema` DEFAULT CHARACTER SET utf8 ;
USE `personal_website_schema` ;

-- -----------------------------------------------------
-- Table `personal_website_schema`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_website_schema`.`messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  `created` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personal_website_schema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_website_schema`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personal_website_schema`.`page_visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_website_schema`.`page_visits` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_id` VARCHAR(255) NULL,
  `datestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
